# [build-system]
# requires = [""]

[tool.setuptools]
packages = ["immrax"]

[project]
name = "immrax"
version = "0.1.0"
dependencies = [
    "numpy",
    "scipy",
    "tqdm",
    "shapely",
    "matplotlib",
    "tabulate",
    "sympy",
    "sympy2jax",
    "jaxtyping",
    "diffrax",
    "equinox",
    "immutabledict",
    "einshape@git+https://github.com/google-deepmind/einshape.git",
    "jax_verify@git+https://github.com/google-deepmind/jax_verify.git",
]
